spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 60000
      max-lifetime: 1800000
      idle-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  h2:
    console:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  external-urls:
    dev-alert-discord-webhook: ${DEV_ALERT_DISCORD_WEBHOOK}
    prod-alert-discord-webhook: ${PROD_ALERT_DISCORD_WEBHOOK}
  token:
    secret-key: ${TOKEN_SECRET_KEY}
