name: 🧑‍💻 Spring boot 개발 환경 CI/CD
on:
  push:
    branches:
      - dev

env:
  ENVIRONMENT: dev
  IMAGE_NAME: sckwon770/easip-server-dev
  SERVICE_NAME: easip-server

jobs:
  prepare-variables:
    name: 워크플로우 변수 준비
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.setup-env.outputs.image-name }}
      image-tag: ${{ steps.setup-env.outputs.image-tag }}
      environment: ${{ steps.setup-env.outputs.environment }}
      service-name: ${{ steps.setup-env.outputs.service-name }}
    steps:
      - name: Github에서 레포 받아오기
        uses: actions/checkout@v3
      - name: 변수 출력하기
        id: setup-env
        run: |
          echo "image-name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "image-tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "service-name=$SERVICE_NAME" >> $GITHUB_OUTPUT

  call-build-workflow:
    if: github.event_name == 'push'
    needs: [ prepare-variables ]
    name: 이미지 빌드
    uses: ./.github/workflows/build.yaml
    permissions:
      id-token: write
      contents: read
    with:
      image-tag: ${{ needs.prepare-variables.outputs.image-tag }}
      image-name: ${{ needs.prepare-variables.outputs.image-name }}
      environment: ${{ needs.prepare-variables.outputs.environment }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  call-deploy-workflow:
    if: github.event_name == 'push'
    needs: [ prepare-variables, call-build-workflow ]
    name: 서비스 배포
    uses: ./.github/workflows/deploy.yaml
    permissions:
      id-token: write
      contents: read
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    with:
      image-name: ${{ needs.prepare-variables.outputs.image-name }}
      image-tag: ${{ needs.prepare-variables.outputs.image-tag }}
      environment: ${{ needs.prepare-variables.outputs.environment }}
      service-name: ${{ needs.prepare-variables.outputs.service-name }}
